# Generated by Django 5.1.4 on 2025-01-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='field1',
            new_name='content',
        ),
    ]
